import { useState, useEffect, useMemo } from 'react';
import { base44 } from '@/api/base44Client';
import { Users, UserPlus, CalendarClock, TrendingUp, Star, Sparkles, Palette, DollarSign } from 'lucide-react';

function Stat({ icon: Icon, label, value, accent }) {
  return (
    <div className="glass-panel border border-vapor/10 rounded-sm p-4">
      <Icon size={18} className={`mb-3 ${accent || 'text-gold/60'}`} />
      <p className="text-2xl font-grotesk font-bold text-vapor">{value}</p>
      <p className="text-xs font-mono-tech tracking-widest text-vapor/40 mt-1">{label}</p>
    </div>
  );
}

export default function BusinessDevTab() {
  const [partners, setPartners] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try { const list = await base44.entities.Partner.list('-created_date', 500); setPartners(list || []); }
      catch (e) { console.error(e); }
      finally { setLoading(false); }
    })();
  }, []);

  const m = useMemo(() => {
    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const active = partners.filter(p => p.status === 'active');
    const newThisMonth = partners.filter(p => new Date(p.created_date) >= monthStart);
    const today = new Intl.DateTimeFormat('en-CA').format(now);
    const followUpsDue = active.filter(p => p.next_follow_up_date && p.next_follow_up_date <= today);
    const totalReferrals = partners.reduce((s, p) => s + (p.referral_count || 0), 0);
    const totalConversions = partners.reduce((s, p) => s + (p.conversions_count || 0), 0);
    const lifetimeRevenue = partners.reduce((s, p) => s + (p.revenue_generated || 0), 0);
    const gold = partners.reduce((s, p) => s + (p.gold_members_generated || 0), 0);
    const coatings = partners.reduce((s, p) => s + (p.ceramic_coatings_generated || 0), 0);
    const corrections = partners.reduce((s, p) => s + (p.paint_corrections_generated || 0), 0);
    const conversionRate = totalReferrals ? Math.round((totalConversions / totalReferrals) * 100) : 0;

    const byDealership = {};
    partners.forEach(p => { const d = p.dealership || 'Independent'; byDealership[d] = (byDealership[d] || 0) + (p.revenue_generated || 0); });
    const topDealerships = Object.entries(byDealership).map(([name, rev]) => ({ name, rev })).sort((a, b) => b.rev - a.rev).slice(0, 5);
    const topPartners = [...partners].sort((a, b) => (b.revenue_generated || 0) - (a.revenue_generated || 0)).slice(0, 5);

    return {
      activeCount: active.length, newThisMonth: newThisMonth.length, followUpsDue: followUpsDue.length,
      totalReferrals, totalConversions, lifetimeRevenue, gold, coatings, corrections, conversionRate,
      topDealerships, topPartners, foundingCount: partners.filter(p => p.is_founding_partner).length,
    };
  }, [partners]);

  if (loading) return <div className="flex justify-center py-20"><div className="w-8 h-8 border-2 border-gold/20 border-t-gold rounded-full animate-spin" /></div>;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-grotesk font-bold text-vapor">Business Development</h1>
        <span className="text-xs font-mono-tech tracking-widest text-vapor/40">{m.foundingCount} FOUNDING · {m.activeCount} ACTIVE</span>
      </div>

      <div className="glass-panel border border-gold/25 rounded-sm p-5 flex items-center gap-4 bg-gold/[0.03]">
        <div className="w-11 h-11 rounded-sm bg-gold/10 border border-gold/30 flex items-center justify-center shrink-0"><DollarSign size={22} className="text-gold" /></div>
        <div>
          <p className="text-3xl font-grotesk font-bold text-gold leading-none">${m.lifetimeRevenue.toLocaleString()}</p>
          <p className="text-xs font-mono-tech tracking-widest text-vapor/50 mt-1.5">LIFETIME REVENUE GENERATED BY PARTNERS</p>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Stat icon={Users} label="ACTIVE PARTNERS" value={m.activeCount} />
        <Stat icon={UserPlus} label="NEW THIS MONTH" value={m.newThisMonth} />
        <Stat icon={CalendarClock} label="FOLLOW-UPS DUE" value={m.followUpsDue} accent="text-amber-300/70" />
        <Stat icon={TrendingUp} label="CONVERSION RATE" value={`${m.conversionRate}%`} />
        <Stat icon={Star} label="GOLD MEMBERS" value={m.gold} />
        <Stat icon={Sparkles} label="CERAMIC COATINGS" value={m.coatings} />
        <Stat icon={Palette} label="PAINT CORRECTIONS" value={m.corrections} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="glass-panel border border-vapor/10 rounded-sm p-5">
          <h2 className="text-xs font-mono-tech tracking-widest text-gold/70 mb-4">TOP DEALERSHIPS</h2>
          {m.topDealerships.length ? (
            <div className="space-y-3">
              {m.topDealerships.map((d, i) => (
                <div key={d.name} className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-3 min-w-0">
                    <span className="text-xs font-mono-tech text-vapor/40 w-4">{i + 1}</span>
                    <span className="text-sm text-vapor/80 font-grotesk truncate">{d.name}</span>
                  </div>
                  <span className="text-xs font-mono-tech text-gold">${d.rev.toLocaleString()}</span>
                </div>
              ))}
            </div>
          ) : <p className="text-center text-vapor/40 font-mono-tech text-sm py-8">No data yet.</p>}
        </div>
        <div className="glass-panel border border-vapor/10 rounded-sm p-5">
          <h2 className="text-xs font-mono-tech tracking-widest text-gold/70 mb-4">TOP PERFORMING PARTNERS</h2>
          {m.topPartners.length ? (
            <div className="space-y-3">
              {m.topPartners.map((p, i) => (
                <div key={p.id} className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-3 min-w-0">
                    <span className="text-xs font-mono-tech text-vapor/40 w-4">{i + 1}</span>
                    <span className="text-sm text-vapor/80 font-grotesk truncate">{p.name}</span>
                  </div>
                  <span className="text-xs font-mono-tech text-gold">${(p.revenue_generated || 0).toLocaleString()}</span>
                </div>
              ))}
            </div>
          ) : <p className="text-center text-vapor/40 font-mono-tech text-sm py-8">No data yet.</p>}
        </div>
      </div>
    </div>
  );
}